stages:
- deploy
deploy:
  stage: deploy
  script:
    - export PATH=$PATH:/opt/node-v6.11.2-linux-x64/bin
    - npm install
    - hexo generate
    - cp public/* /var/www/osc.shu.edu.cn -R

  only:
    - master
  tags:
    - shell